name: Blackbox Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  backend-lint-and-tests:
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Setup cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-pip
    - name: Install poetry
      run: pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: setup-docker
      uses: docker-practice/actions-setup-docker@0.0.1
    - name: Linting backend
      run: poetry run sh scripts/lint.sh
    - name: Run unittests
      run: poetry run sh scripts/unittest.sh
    - name: Run blackbox tests
      run: poetry run sh scripts/blackbox_test.sh
  frontend-lint:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install
    - run: npm run lint